"""Add favorite movies

Revision ID: d7ad4c776c27
Revises: 3aa18fd42ab8
Create Date: 2025-03-14 19:25:06.150837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ad4c776c27'
down_revision = '3aa18fd42ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('release_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_movies', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('favorite_movies')

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('release_date',
               existing_type=sa.String(length=100),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
